/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pratikum29062026;

import java.awt.HeadlessException;

/**
 *
 * @author LUTVI
 */
public class FormMinuman extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMinuman.class.getName());

    /**
     * Creates new form FormMinuman
     */
    
    private MenuUtama utama;
    
    public FormMinuman() {
        initComponents();
    }

    public FormMinuman(MenuUtama utama) throws HeadlessException {
        this.utama = utama;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ckbTeh = new javax.swing.JCheckBox();
        ckbCendol = new javax.swing.JCheckBox();
        ckbAir = new javax.swing.JCheckBox();
        txtEsTeh = new javax.swing.JTextField();
        txtCendol = new javax.swing.JTextField();
        txtAir = new javax.swing.JTextField();
        cbEsTeh = new javax.swing.JComboBox<>();
        cbAir = new javax.swing.JComboBox<>();
        cbCendol = new javax.swing.JComboBox<>();
        txtTotalEsTeh = new javax.swing.JTextField();
        txtTotalCendol = new javax.swing.JTextField();
        txtTotalAir = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        btnTotalHarga = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pilih Minuman");

        ckbTeh.setText("Es Teh");
        ckbTeh.addActionListener(this::ckbTehActionPerformed);

        ckbCendol.setText("Cendol");
        ckbCendol.addActionListener(this::ckbCendolActionPerformed);

        ckbAir.setText("Air Putih");
        ckbAir.addActionListener(this::ckbAirActionPerformed);

        txtEsTeh.setText("0");

        txtCendol.setText("0");

        txtAir.setText("0");
        txtAir.addActionListener(this::txtAirActionPerformed);

        cbEsTeh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbEsTeh.addActionListener(this::cbEsTehActionPerformed);

        cbAir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbAir.addActionListener(this::cbAirActionPerformed);

        cbCendol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbCendol.addActionListener(this::cbCendolActionPerformed);

        txtTotalEsTeh.setText("0");

        txtTotalCendol.setText("0");

        txtTotalAir.setText("0");

        txtTotalHarga.setText("0");

        btnTotalHarga.setText("Lihat Harga");
        btnTotalHarga.addActionListener(this::btnTotalHargaActionPerformed);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ckbCendol, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckbTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckbAir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCendol, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbAir, 0, 90, Short.MAX_VALUE)
                                    .addComponent(cbEsTeh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbCendol, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnTotalHarga)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalEsTeh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalCendol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalAir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbTeh)
                    .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbCendol)
                    .addComponent(txtCendol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCendol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalCendol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbAir)
                    .addComponent(txtAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalAir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotalHarga))
                .addGap(37, 37, 37)
                .addComponent(btnKembali)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirActionPerformed

    private void btnTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalHargaActionPerformed
        double a = Double.parseDouble(txtTotalEsTeh.getText());
            double b = Double.parseDouble(txtTotalCendol.getText());
            double c = Double.parseDouble(txtTotalAir.getText());
            double total = a+b+c;
            
            txtTotalHarga.setText(Double.toString(total));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTotalHargaActionPerformed

    private void ckbTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbTehActionPerformed
        txtEsTeh.setText("5000");
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbTehActionPerformed

    private void ckbCendolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbCendolActionPerformed
         txtCendol.setText("7000");
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbCendolActionPerformed

    private void ckbAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbAirActionPerformed
         txtAir.setText("2000");
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbAirActionPerformed

    private void cbEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEsTehActionPerformed
        int jumlah = (int)cbEsTeh.getSelectedIndex();
            double harga = Double.parseDouble(txtEsTeh.getText());
            double total = jumlah * harga;
            txtTotalEsTeh.setText(Double.toString(total));
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEsTehActionPerformed

    private void cbCendolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCendolActionPerformed
        int jumlah = (int)cbCendol.getSelectedIndex();
            double harga = Double.parseDouble(txtCendol.getText());
            double total = jumlah * harga;
            txtTotalCendol.setText(Double.toString(total));
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCendolActionPerformed

    private void cbAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAirActionPerformed
        int jumlah = (int)cbAir.getSelectedIndex();
            double harga = Double.parseDouble(txtAir.getText());
            double total = jumlah * harga;
            txtTotalAir.setText(Double.toString(total));
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAirActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotalHarga.getText();
            utama.setTotalMinuman(total);
            this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMinuman().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotalHarga;
    private javax.swing.JComboBox<String> cbAir;
    private javax.swing.JComboBox<String> cbCendol;
    private javax.swing.JComboBox<String> cbEsTeh;
    private javax.swing.JCheckBox ckbAir;
    private javax.swing.JCheckBox ckbCendol;
    private javax.swing.JCheckBox ckbTeh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAir;
    private javax.swing.JTextField txtCendol;
    private javax.swing.JTextField txtEsTeh;
    private javax.swing.JTextField txtTotalAir;
    private javax.swing.JTextField txtTotalCendol;
    private javax.swing.JTextField txtTotalEsTeh;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
