/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pratikum29062026;

import java.awt.HeadlessException;

/**
 *
 * @author LUTVI
 */
public class FormMakanan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMakanan.class.getName());

    /**
     * Creates new form FormMenuMakanan
     */
    private MenuUtama utama;
    
    public FormMakanan() {
        initComponents();
    }

    public FormMakanan(MenuUtama utama) throws HeadlessException {
        this.utama = utama;
        initComponents();
    }
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        ckbAyam = new javax.swing.JCheckBox();
        ckbIkan = new javax.swing.JCheckBox();
        ckbMie = new javax.swing.JCheckBox();
        txtAyam = new javax.swing.JTextField();
        txtIkan = new javax.swing.JTextField();
        txtMie = new javax.swing.JTextField();
        cbAyam = new javax.swing.JComboBox<>();
        cbIkan = new javax.swing.JComboBox<>();
        cbMie = new javax.swing.JComboBox<>();
        txtTotalAyam = new javax.swing.JTextField();
        txtTotalIkan = new javax.swing.JTextField();
        txtTotalMie = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnTotalHarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJudul.setText("Pilihan Menu Makanan");

        ckbAyam.setText("Ayam chicken");
        ckbAyam.addActionListener(this::ckbAyamActionPerformed);

        ckbIkan.setText("Chicken Fish");
        ckbIkan.addActionListener(this::ckbIkanActionPerformed);

        ckbMie.setText("Mie Ayam");
        ckbMie.addActionListener(this::ckbMieActionPerformed);

        txtAyam.setText("0");
        txtAyam.addActionListener(this::txtAyamActionPerformed);

        txtIkan.setText("0");

        txtMie.setText("0");

        cbAyam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbAyam.addActionListener(this::cbAyamActionPerformed);

        cbIkan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbIkan.addActionListener(this::cbIkanActionPerformed);

        cbMie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMie.addActionListener(this::cbMieActionPerformed);

        txtTotalAyam.setText("0");

        txtTotalIkan.setText("0");

        txtTotalMie.setText("0");

        txtTotalHarga.setText("0");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        btnTotalHarga.setText("Lihat Harga");
        btnTotalHarga.addActionListener(this::btnTotalHargaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ckbMie, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMie, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ckbIkan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIkan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ckbAyam, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAyam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbIkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbMie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnTotalHarga))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalIkan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalAyam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalMie, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btnKembali)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblJudul)
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbAyam)
                    .addComponent(txtAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbIkan)
                    .addComponent(txtIkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbIkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalIkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbMie)
                    .addComponent(txtMie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotalHarga))
                .addGap(51, 51, 51)
                .addComponent(btnKembali)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbAyamActionPerformed
            txtAyam.setText("15000");
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbAyamActionPerformed

    private void ckbIkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbIkanActionPerformed
             txtIkan.setText("25000");
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbIkanActionPerformed

    private void ckbMieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMieActionPerformed
             txtMie.setText("10000");
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbMieActionPerformed

    private void cbAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAyamActionPerformed
            int jumlah = (int)cbAyam.getSelectedIndex();
            double harga = Double.parseDouble(txtAyam.getText());
            double total = jumlah * harga;
            txtTotalAyam.setText(Double.toString(total));
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAyamActionPerformed

    private void cbIkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIkanActionPerformed
            int jumlah = (int)cbIkan.getSelectedIndex();
            double harga = Double.parseDouble(txtIkan.getText());
            double total = jumlah * harga;
            txtTotalIkan.setText(Double.toString(total));
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIkanActionPerformed

    private void cbMieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMieActionPerformed
            int jumlah = (int)cbMie.getSelectedIndex();
            double harga = Double.parseDouble(txtMie.getText());
            double total = jumlah * harga;
            txtTotalMie.setText(Double.toString(total));
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMieActionPerformed

    private void btnTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalHargaActionPerformed
            double a = Double.parseDouble(txtTotalAyam.getText());
            double b = Double.parseDouble(txtTotalIkan.getText());
            double c = Double.parseDouble(txtTotalMie.getText());
            double total = a+b+c;
            
            txtTotalHarga.setText(Double.toString(total));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTotalHargaActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
            String total = txtTotalHarga.getText();
            utama.setTotalMakanan(total);
            this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAyamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAyamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMakanan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotalHarga;
    private javax.swing.JComboBox<String> cbAyam;
    private javax.swing.JComboBox<String> cbIkan;
    private javax.swing.JComboBox<String> cbMie;
    private javax.swing.JCheckBox ckbAyam;
    private javax.swing.JCheckBox ckbIkan;
    private javax.swing.JCheckBox ckbMie;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JTextField txtAyam;
    private javax.swing.JTextField txtIkan;
    private javax.swing.JTextField txtMie;
    private javax.swing.JTextField txtTotalAyam;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextField txtTotalIkan;
    private javax.swing.JTextField txtTotalMie;
    // End of variables declaration//GEN-END:variables
}
