/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pratikum22062026;

import javax.swing.JOptionPane;

/**
 *
 * @author LUTVI
 */
public class FormTiket extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiket.class.getName());

    /**
     * Creates new form FormTiket
     */
    public FormTiket() {
        initComponents();
        txtHarga.setEditable(false);
        txtTotal.setEditable(false);
        txtDiskon.setEditable(false);
        txtBayar.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtn1 = new javax.swing.ButtonGroup();
        rbbkt = new javax.swing.JRadioButton();
        rbsolok = new javax.swing.JRadioButton();
        rbpar = new javax.swing.JRadioButton();
        cbKelas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnharga = new javax.swing.JButton();
        txtHarga = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbltot = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblDiskon = new javax.swing.JLabel();
        lbltompen = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gbtn1.add(rbbkt);
        rbbkt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbbkt.setText("Bukit Tinggi");
        rbbkt.addActionListener(this::rbbktActionPerformed);

        gbtn1.add(rbsolok);
        rbsolok.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbsolok.setText("Solok");
        rbsolok.addActionListener(this::rbsolokActionPerformed);

        gbtn1.add(rbpar);
        rbpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbpar.setText("Pariaman");

        cbKelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Kelas", "Ekonomi", "Bisnis", "Eksekutif" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("FORM PEMBELIAN TIKET BUS NUSANTARA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tujuan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Kelas");

        btnharga.setText("Harga 1 Tiket");
        btnharga.addActionListener(this::btnhargaActionPerformed);

        txtjumlah.addActionListener(this::txtjumlahActionPerformed);

        jLabel4.setText("Masukkan Jumlah Tiket");

        lbltot.setText("Total Harga");

        txtTotal.addActionListener(this::txtTotalActionPerformed);

        lblDiskon.setText("Diskon");

        lbltompen.setText("totalPembayaran");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(this::btnHitungActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnharga)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbbkt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbsolok)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbpar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(btnHitung))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblDiskon)
                                                    .addComponent(lbltot))
                                                .addGap(46, 46, 46))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lbltompen)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(49, 49, 49))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnReset)
                        .addGap(70, 70, 70)
                        .addComponent(btnKeluar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbbkt)
                    .addComponent(rbsolok, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnharga)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lbltot)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiskon)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltompen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluar)
                    .addComponent(btnReset))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbbktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbbktActionPerformed

    private void rbsolokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsolokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbsolokActionPerformed

    private void btnhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhargaActionPerformed

        int kelas= (int)cbKelas.getSelectedIndex();
        
        if(!rbbkt.isSelected()&&!rbsolok.isSelected()&&!rbpar.isSelected()){
            JOptionPane.showMessageDialog(this,"pilih dulu lah");
        } else if(cbKelas.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Kelas belum di pilih");
        }
        
        switch(kelas){
            case 1 : if(rbbkt.isSelected())
                        txtHarga.setText("25000");
            
                    else if(rbsolok.isSelected())
                        txtHarga.setText("20000");
                
                    else
                        txtHarga.setText("15000");
                    break;
                    
            case 2 : if(rbbkt.isSelected())
                        txtHarga.setText("50000");
            
                    else if(rbsolok.isSelected())
                        txtHarga.setText("40000");
                
                    else
                        txtHarga.setText("30000");
                    break;
                    
            case 3 : if(rbbkt.isSelected())
                        txtHarga.setText("80000");
            
                    else if(rbsolok.isSelected())
                        txtHarga.setText("75000");
                
                    else
                        txtHarga.setText("55000");
                    break;
                    
                    
                    
                            
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_btnhargaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        
        txtHarga.setText("");
        txtjumlah.setText("");
        txtTotal.setText("");
        txtDiskon.setText("");
        txtBayar.setText("");
        cbKelas.setSelectedIndex(0);
        gbtn1.clearSelection();
            // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
    try{
        int jumlah = Integer.parseInt(txtjumlah.getText());
        if (jumlah<0){
            JOptionPane.showMessageDialog(this,"jumlah tiket lebih dari 0");
            txtjumlah.setText("");
            txtjumlah.requestFocus();
        }else{
        double harga = Double.parseDouble(txtHarga.getText());
        double total = jumlah * harga;
        double diskon = 0;
        if(jumlah>5)
            diskon = 0.1 * total;
        double bayar = total-diskon;
        
        txtTotal.setText(Double.toString(total));
        txtDiskon.setText(Double.toString(diskon));
        txtBayar.setText(Double.toString(bayar));
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Jumlah harus bilangan bulat");
            txtjumlah.setText("");
            txtjumlah.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int pil = JOptionPane.showConfirmDialog(this,"Apkah ingin Keluar","Konfirmasi",JOptionPane.YES_NO_OPTION);
        
        if(pil==JOptionPane.YES_OPTION)
            System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTiket().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnharga;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.ButtonGroup gbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lbltompen;
    private javax.swing.JLabel lbltot;
    private javax.swing.JRadioButton rbbkt;
    private javax.swing.JRadioButton rbpar;
    private javax.swing.JRadioButton rbsolok;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtjumlah;
    // End of variables declaration//GEN-END:variables
}
