/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FormGaji;

import javax.swing.JOptionPane;

/**
 *
 * @author LUTVI
 */
public class FormGaji extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormGaji.class.getName());

    /**
     * Creates new form FormGaji
     */
    public FormGaji() {
        initComponents();
        editTotal.setEditable(false);
        editGaji.setEditable(false);
        editPajak.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtn1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtPilGolongan = new javax.swing.JLabel();
        txtPilStatus = new javax.swing.JLabel();
        txtJam = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtPajak = new javax.swing.JLabel();
        txtGaji = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        editNama = new javax.swing.JTextField();
        rbTidak = new javax.swing.JRadioButton();
        rbMenikah = new javax.swing.JRadioButton();
        pilGolongan = new javax.swing.JComboBox<>();
        editJam = new javax.swing.JTextField();
        editTotal = new javax.swing.JTextField();
        editPajak = new javax.swing.JTextField();
        editGaji = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Form Pengajian Karyawan");

        txtNama.setText("Masukkan Nama Anda");

        txtPilGolongan.setText("Pilih Golongan");

        txtPilStatus.setText("Pillih Status");

        txtJam.setText("Masukkan Jam Kerja");

        txtTotal.setText("Total");

        txtPajak.setText("Pajak");

        txtGaji.setText("Gaji Bersih");

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        editNama.addActionListener(this::editNamaActionPerformed);

        gbtn1.add(rbTidak);
        rbTidak.setText("Tidak");
        rbTidak.addActionListener(this::rbTidakActionPerformed);

        gbtn1.add(rbMenikah);
        rbMenikah.setText("Menikah");
        rbMenikah.addActionListener(this::rbMenikahActionPerformed);

        pilGolongan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Pilih", "Golongan 1", "Golongan 2", "Golongan 3", "Golongan 4" }));
        pilGolongan.addActionListener(this::pilGolonganActionPerformed);

        editJam.addActionListener(this::editJamActionPerformed);

        editTotal.addActionListener(this::editTotalActionPerformed);

        editPajak.addActionListener(this::editPajakActionPerformed);

        editGaji.addActionListener(this::editGajiActionPerformed);

        btnProses.setText("Lihat");
        btnProses.addActionListener(this::btnProsesActionPerformed);

        jLabel2.setText("Lihat Gaji Anda bulan Ini");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPilGolongan)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPilStatus)
                                            .addComponent(txtJam))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rbMenikah)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rbTidak))
                                            .addComponent(editJam, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pilGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editNama, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(txtGaji)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(editPajak)
                                    .addComponent(editGaji))))
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnReset)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnProses)))
                                .addGap(18, 18, 18)
                                .addComponent(btnKeluar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPajak)
                                .addComponent(txtTotal)))
                        .addGap(22, 22, 22)))
                .addContainerGap(6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPilGolongan)
                    .addComponent(pilGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPilStatus)
                    .addComponent(rbMenikah)
                    .addComponent(rbTidak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJam)
                    .addComponent(editJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProses)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal)
                    .addComponent(editTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPajak)
                    .addComponent(editPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGaji)
                    .addComponent(editGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        editNama.setText("");
        pilGolongan.setSelectedIndex(0);
        gbtn1.clearSelection();
        editJam.setText("");
        editTotal.setText("");
        editPajak.setText("");
        editGaji.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void editNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNamaActionPerformed

    private void pilGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilGolonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilGolonganActionPerformed

    private void rbMenikahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMenikahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMenikahActionPerformed

    private void rbTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTidakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTidakActionPerformed

    private void editJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editJamActionPerformed

    private void editTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTotalActionPerformed

    private void editPajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPajakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPajakActionPerformed

    private void editGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editGajiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        int pil = JOptionPane.showConfirmDialog(this,"Apkah ingin Keluar","Konfirmasi",JOptionPane.YES_NO_OPTION);
        
        if(pil==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        
        int Jam = Integer.parseInt(editJam.getText());
        
        
        if(!rbMenikah.isSelected()&&!rbTidak.isSelected()){
            JOptionPane.showMessageDialog(this,"pilih dulu lah");
        } else if(pilGolongan.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Kelas belum di pilih");
        }
        
        if (Jam<0){
            JOptionPane.showMessageDialog(this,"jumlah Jam lebih dari 0");
            editJam.setText("");
            editJam.requestFocus();
        }else{
        double Tunjangan = 0;
        double Gapok = 0;
        int kelas = pilGolongan.getSelectedIndex();
        
        switch(kelas){
            case 1 -> {
                if(rbMenikah.isSelected()){
                    Tunjangan = 1000000;
                    Gapok     = 5000000;
                }else{
                    Tunjangan = 0;
                    Gapok     = 5000000;
                }
                }
                    
            case 2 -> {
                if(rbMenikah.isSelected()){
                    Tunjangan = 2000000;
                    Gapok     = 6000000;
                }else{
                    Tunjangan = 0;
                    Gapok     = 6000000;
                }
                }
                 
            case 3 -> {
                if(rbMenikah.isSelected()){
                    Tunjangan = 3000000;
                    Gapok     = 7000000;
                }else{
                    Tunjangan = 0;
                    Gapok     = 7000000;
                }
                }
                    
            case 4 -> {
                if(rbMenikah.isSelected()){
                    Tunjangan = 4000000;
                    Gapok     = 8000000;
                }else{
                    Tunjangan = 0;
                    Gapok     = 8000000;
                }
                }
        }
        double Total = Tunjangan+Gapok+(Jam*25000);
        
        double Pajak = Total*0.25;
        
        double Gaji = Total - Pajak;
        
        editTotal.setText(Double.toString(Total));
        editPajak.setText(Double.toString(Pajak));
        editGaji.setText(Double.toString(Gaji));
    }
        
                    
                    
                    
    }//GEN-LAST:event_btnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormGaji().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField editGaji;
    private javax.swing.JTextField editJam;
    private javax.swing.JTextField editNama;
    private javax.swing.JTextField editPajak;
    private javax.swing.JTextField editTotal;
    private javax.swing.ButtonGroup gbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> pilGolongan;
    private javax.swing.JRadioButton rbMenikah;
    private javax.swing.JRadioButton rbTidak;
    private javax.swing.JLabel txtGaji;
    private javax.swing.JLabel txtJam;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtPajak;
    private javax.swing.JLabel txtPilGolongan;
    private javax.swing.JLabel txtPilStatus;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
